<html>
	<head>
		<style>
			table {
				font: 6px arial;
			}
			table {
				width:667px;
			}

			td {
				border-bottom: 1px solid black;
				border-left: 5px solid #fbd11a;
				height:30px;
				vertical-align: top;
			}

			td span {
				font-size: 8px;
				color: blue;
				display:block;
				text-align:left !important;
			}

			.fundo_amarelo {
				background-color: #FFFF99;
			}

			.branco {
				border: none !important;
				height: 20px;
			}

			.codigo_banco {
				text-align:center;
				font-size:16px;
				width:50px;
			}

			.linha_digitavel {
				text-align:right;
				font-size:14px;
			}

			.codigo_banco, .linha_digitavel {
				border-left: 1px solid black !important;
				vertical-align: bottom !important;
				color:#000099;
				font-weight: bold;
			}

			.direita {
				text-align: right;
			}

			.logo{
				border-left: none !important;
				vertical-align: bottom !important;
			}

			.instrucoes {
				border-left: none !important;
				font:11px arial !important;
			}

			.first {
				width:180px;
			}
			.last {
				width:160px;
			}

			.cortar {
				width:667px;
				height: 10px;
				border-bottom: 1px dashed;
				text-align: right;
				font: 6px arial;
				padding-bottom: 4px;
				margin-top: -9px;
			}

			.table1 {
				margin-bottom: 80px;
			}

			img.barcode_img {
				margin-top:8px;
			}
		</style>
	</head>
	<body>
		<table class="table1">
			<tr>
				<td class="logo"colspan="2" rowspan="2"><img  src="data:image/x-icon;base64,<?php echo $this->vars['logo'] ?>"/></td>
				<td colspan="8" class="branco"></td>
			</tr>
			<tr>
				<td class="codigo_banco">001-9</td>
				<td colspan="7" class="linha_digitavel"><?php echo $this->vars['linha_digitavel'] ?></td>
			</tr>
			<tr>
				<td colspan="3">
					<span>Cedente</span>
					<?php echo $this->vars['nome_cedente'] ?>
				</td>
				<td colspan="5">
					<span>Agência/Codigo Cedente</span>
					<?php echo $this->vars['agencia'].' / '.$this->vars['conta']?>
				</td>
				<td>
					<span>Especie</span>
					<?php echo $this->vars['especie'] ?>
				</td>
				<td class="direita last">
					<span>Nosso Número</span>
					<?php echo $this->vars['nosso_numero'] ?>
				</td>
			</tr>
			<tr>
				<td colspan="3">
					<span>Nº Documento</span>
				</td>
				<td colspan="3">
					<span>Data Documento</span>
					<?php echo $this->vars['data_hoje']?>
				</td>
				<td colspan="3" class="fundo_amarelo">
					<span>Vencimento</span>
					<?php echo $this->vars['vencimento']?>
				</td>
				<td class="direita">
					<span>(=) Valor do Documento</span>
					<?php echo $this->vars['valor'] ?>
				</td>
			</tr>

			<tr>
				<td><span>(-) Desconto</span></td>
				<td colspan="4"><span>(-) Outras Deduções</span></td>
				<td colspan="3"><span>(+) Juros / Multa</span></td>
				<td colspan="1"><span>(+) Outros Acréscimos</span></td>
				<td class="direita fundo_amarelo"><span>(=) Valor Cobrado</span></td>
			</tr>
			<tr>
				<td colspan="10">
					<span>Sacado:</span>
					<?php echo $this->vars['cliente_nome']?><br/>
					<?php echo $this->vars['cliente_endereco']?><br/>
					<?php echo $this->vars['cliente_cidade']?> - <?php echo $this->vars['cliente_uf']?> - CEP:<?php echo $this->vars['cliente_cep']?>
				</td>
			</tr>
		</table>

<div class="cortar">Corte aqui</div>

		<table>
			<tr>
				<td class="logo"colspan="2" rowspan="2"><img  src="data:image/x-icon;base64,<?php echo $this->vars['logo'] ?>"/></td>
				<td colspan="8" class="branco"></td>
			</tr>
			<tr>
				<td class="codigo_banco">001-9</td>
				<td colspan="7" class="linha_digitavel"><?php echo $this->vars['linha_digitavel'] ?></td>
			</tr>
			<tr>
				<td colspan="9">
					<span>Local Pagamento</span>
					Pagável em qualquer Banco até o vencimento
				</td>
				<td class="fundo_amarelo direita last">
					<span>Vencimento</span>
					<?php echo $this->vars['vencimento'] ?>
				</td>
			</tr>
			<tr>
				<td colspan="9">
					<span>Cedente</span>
					<?php echo $this->vars['nome_cedente']; ?>
				</td>
				<td class="direita">
					<span>Agência/Codigo Cedente</span>
					<?php echo $this->vars['agencia'].' / '.$this->vars['conta']?>
				</td>
			</tr>
			<tr>
				<td class="first">
					<span>Data Documento</span>
					<?php echo $this->vars['data_hoje'] ?>
				</td>
				<td colspan="5">
					<span>Nº documento</span>
				</td>
				<td>
					<span>Espécie DOC</span>
				</td>
				<td>
					<span>Aceite</span>
					N
				</td>
				<td>
					<span>Data process.</span>
					<?php echo $this->vars['data_hoje'] ?>
				</td>
				<td class="direita">
					<span>Nosso número</span>
					<?php echo $this->vars['nosso_numero']?>
				</td>
			</tr>
			<tr>
				<td class="fundo_amarelo"><span>Uso do Banco</span></td>
				<td colspan="3">
					<span>Carteira</span>
					<?php echo $this->vars['carteira'] ?>
				</td>
				<td>
					<span>Especie</span>
					<?php echo $this->vars['especie'] ?>
				</td>
				<td colspan="3">
					<span>Quantidade</span>
				</td>
				<td>
					<span>Valor</span>
				</td>
				<td class="direita">
					<span>(=) Valor do Documento</span>
					<?php echo $this->vars['valor'] ?>
				</td>
			</tr>
			<tr>
				<td rowspan="5" colspan="9" class="instrucoes">
					<span>Instruções:</span>
					<p><strong>Não receber após a data de vencimento.</strong></p>
					<p>Atenção Sr(a). Cliente:</p>
					<p>O pedido ficará pendente até; que este boleto seja pago.</p>
					<p>Não confunda pagamento com agendamento, pague o boleto com a data do próprio dia.</p>
				
				</td>
				<td class="direita"><span>(-) Desconto / Abatimentos</span></td>
			</tr>
			<tr>
				<td class="direita"><span>(-) Outras Deduções</span></td>
			</tr>
			<tr>
				<td class="direita"><span>(+) Juros / Multa</span></td>
			</tr>
			<tr>
				<td class="direita"><span>(+) Outros Acrescimos</span></td>
			</tr>
			<tr>
				<td class="fundo_amarelo esquerda">
					<span>(=) Valor Cobrado</span>
				</td>
			</tr>
			<tr>
				<td colspan="10">
					<span>Sacado:</span>
					<?php echo $this->vars['cliente_nome']?><br/>
					<?php echo $this->vars['cliente_endereco']?><br/>
					<?php echo $this->vars['cliente_cidade']?> - <?php echo $this->vars['cliente_uf']?> - CEP:<?php echo $this->vars['cliente_cep']?>
				</td>
			</tr>
		</table>
		<img class="barcode_img" src="data:image/x-icon;base64,<?php echo $this->vars['barcode'] ?>"/>
		<div class="cortar">Corte aqui</div>
	</body>
</html>
