<?php
if (!empty($this->errors)) {
	$errors = $this->xml->addChild('errors');
	$cont = 1;
	foreach ($this->errors as $campo => $value) {
		if (is_array($value)) {
			$error = $errors->addChild('erro_'.$cont++);
			$error->addChild('campo',$campo);
			$cont1 = 1;
			foreach ($value as $erro => $descricao) {
				$error->addChild('tipo_'.$cont1,$erro);
				$error->addChild('descricao_'.$cont1++, $descricao);
			}
		} else {
			$errors->addChild('error',1);
			$errors->addChild('descricao',utf8_encode($value));
		}
	}
} else {
	$this->xml->addChild('errors', '0');
	$this->xml->addChild('boleto', utf8_encode($this->render('boleto/'.$this->boleto_nome.'.phtml')));
}
	header('Content-type: text/xml; charset=iso-8859-1');
	echo $this->xml->asXML();